name: Cancel

on: [ pull_request ]

jobs:
  cancel:
    name: 'Cancel previous runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1472340
          access_token: ${{ github.token }}
