name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: "Build (Linux)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Init
      run: |
        scripts/init.sh
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
  build-macos:
    name: "Build (MacOS)"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Init
      run: |
        scripts/init.sh
    - name: Build
      run: cargo build --verbose --release
  build-win:
    name: "Build (Windows)"
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Rust init
      run: |
        rustup update nightly
        rustup update stable
        rustup target add wasm32-unknown-unknown --toolchain nightly
    - name: Build
      run: |
        set LIBCLANG_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin
        cargo build --release
